import { customTheme } from "@/utils/customTheme";
import { Box } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import StyledLayoutContainer from "@/components/StyledLayoutContainer";

const matteoRegular = localFont({
  src: "./fonts/Matteo-Regular.ttf",
  variable: "--font-matteo-regular",
  weight: "100 900",
});

const playfairFont = localFont({
  src: "./fonts/PlayfairDisplay-Black.woff",
  variable: "--font-playfair",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "The Morning Context",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={`${playfairFont.variable} ${matteoRegular.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={customTheme}>
            <StyledLayoutContainer>{props.children}</StyledLayoutContainer>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
